sudo: required
services:
  - docker

before_install:
  - docker build -t johnschult/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true johnschult/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: docker-react
  env:  DockerReact-env
  bucket_name: elasticbeanstalk-us-east-1-446808491778
  bucket_path: docker-react
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access-key:
    secure: "$AWS_SECRET_KEY"
